import path from 'node:path'
import { PGlite } from '@electric-sql/pglite'
import { drizzle } from 'drizzle-orm/pglite'
import { migrate } from 'drizzle-orm/pglite/migrator'
import * as schema from './schema'

/**
 * Dev database: in-process PostgreSQL (PGlite/WASM) — the same Postgres engine
 * with zero external services (PRD §10.2 targets PostgreSQL 16 in production;
 * swapping to node-postgres + DATABASE_URL is a driver change in this file).
 *
 * Migrations come from `backend/drizzle` (generated by `bun run db:generate`,
 * see drizzle.config.ts) and are applied idempotently on boot.
 */
const client = new PGlite()

export const db = drizzle(client, { schema })

await migrate(db, {
  migrationsFolder: path.join(import.meta.dir, '../../drizzle')
})
